language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable
  firefox: latest

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn --prefer-offline --frozen-lockfile --ignore-engines

script:
  - yarn test
